routes/web.php
<?php

use App\Http\Controllers\Auth\Partner\AuthenticatedSessionController as PartnerAuthenticatedSessionController;
use App\Http\Controllers\Auth\Partner\RegisterController;
use App\Http\Controllers\Auth\Partner\RegisterSuccessController;
use App\Http\Controllers\Auth\Patient\AuthenticatedSessionController as PatientAuthenticatedSessionController;
use App\Http\Controllers\Auth\Patient\RegisterController as PatientRegisterController;
use App\Http\Controllers\Auth\Patient\RegisterSuccessController as PatientRegisterSuccessController;
use App\Http\Controllers\Front\ChangeEmailController;
use App\Http\Controllers\Front\Partner\BankAccountController;
use App\Http\Controllers\Front\Partner\BookingPasscodeController;
use App\Http\Controllers\Front\Partner\DashboardController as PartnerDashboardController;
use App\Http\Controllers\Front\Partner\MapOrderController;
use App\Http\Controllers\Front\Partner\OrderCompletionController;
use App\Http\Controllers\Front\Partner\OrderController;
use App\Http\Controllers\Front\Partner\PaymentCheckOrderController;
use App\Http\Controllers\Front\Partner\PopupAdditionalServicesOrderController;
use App\Http\Controllers\Front\Partner\PopupConfirmationAdditionalServiceOrderController;
use App\Http\Controllers\Front\Partner\PopupHandlingOrderController;
use App\Http\Controllers\Front\Partner\PopupMedicalRecordOrderController;
use App\Http\Controllers\Front\Partner\ProfileController as ProfilePartnerController;
use App\Http\Controllers\Front\Partner\UpdateAvatarController;
use App\Http\Controllers\Front\Partner\WaitingVerification;
use App\Http\Controllers\Front\Patient\BookingCancelController;
use App\Http\Controllers\Front\Patient\BookingController;
use App\Http\Controllers\Front\Patient\BookingInvoiceTableController;
use App\Http\Controllers\Front\Patient\BookingSuccessController;
use App\Http\Controllers\Front\Patient\ClinicServiceController;
use App\Http\Controllers\Front\Patient\ClinicServiceSuccessController;
use App\Http\Controllers\Front\Patient\DashboardController;
use App\Http\Controllers\Front\Patient\MedicalRecordController;
use App\Http\Controllers\Front\Patient\ProfileController;
use App\Http\Controllers\Front\Patient\UpdateAvatarController as UpdateAvatarPatientController;
use App\Http\Controllers\Front\PostalCodeController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\XenditCallbackController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('front.')->group(function() {
    Route::get('/', [FrontController::class, 'index'])->name('index');
    Route::get('/syaratdanketentuan', function () {
        return view('front.syaratdanketentuan');
    })->name('syaratdanketentuan');

    Route::get('/faq', function () {
        return view('front.faq');
    })->name('faq');

    Route::get('/tentang-kami', function () {
        return view('front.tentangkami');
    })->name('tentangkami');


    //Layanan Online Page
    Route::get('/home-visit', function () { return view('front.homevisit'); })->name('home-visit');
    Route::get('/home-care', function () { return view('front.homecare'); })->name('home-care');
    Route::get('/home-covid', function () { return view('front.homecovid'); })->name('home-covid');
    Route::get('/vanilla-clinic', function () { return view('front.vanillaclinic'); })->name('vanilla-clinic');


    //Klinik Kamirawat
    Route::get('/konsultasi-dokter', function () { return view('front.konsultasidokter'); })->name('konsultasi-dokter');
    Route::get('/klinik-diabetes', function () { return view('front.klinikdiabetes'); })->name('klinik-diabetes');
    Route::get('/calm-clinic', function () { return view('front.calmclinic'); })->name('calm-clinic');

    Route::get('/promo', function () { return view('front.promo'); })->name('promo');
    Route::get('/blog', function () { return view('front.blog'); })->name('blog');



    Route::post('/postal-code', [PostalCodeController::class, 'index'])->middleware('guest')->name('postal-code');
    Route::post('/change-email', [ChangeEmailController::class, 'store'])->name('change-email');
    Route::get('/change-email/confirm', [ChangeEmailController::class, 'update'])->name('confirm-change-email');

    Route::prefix('patient')->name('patient.')->group(function() {
        Route::get('/login', [PatientAuthenticatedSessionController::class, 'create'])->middleware('guest')->name('login');
        Route::post('/login', [PatientAuthenticatedSessionController::class, 'store'])->middleware('guest');
        Route::post('/logout', [PatientAuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');
        Route::get('/register', [PatientRegisterController::class, 'create'])->middleware('guest')->name('register');
        Route::post('/register', [PatientRegisterController::class, 'store'])->middleware('guest');
        Route::get('/success', [PatientRegisterSuccessController::class, 'index'])->name('register.success');

        Route::middleware(['auth', 'verified'])->group(function() {
            Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
            Route::put('/profile/avatar', [UpdateAvatarPatientController::class, 'update'])->name('dashboard.update-avatar');
            Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
            Route::put('/profile/email', [ProfileController::class, 'update_email'])->name('profile.update-email');

            Route::get('/bookings', [BookingController::class, 'index'])->name('booking.history');
            Route::put('/booking/cancel/{booking}', [BookingCancelController::class, 'update'])->name('booking.cancel');
            Route::get('/booking/success', [BookingSuccessController::class, 'index'])->name('booking.success');
            Route::get('/booking/{medicalServiceCategory}', [BookingController::class, 'create'])->name('booking.create');
            Route::post('/booking/{medicalServiceCategory}', [BookingController::class, 'store'])->name('booking.store');
            Route::get('/booking/invoice-table/{medicalServiceCategory}', [BookingInvoiceTableController::class, 'index'])->name('booking.invoice-table');

            Route::get('/clinic-service/{medicalServiceCategory}', [ClinicServiceController::class, 'create'])->name('clinic-service.create');
            Route::post('/clinic-service/{medicalServiceCategory}', [ClinicServiceController::class, 'store'])->name('clinic-service.store');
            Route::get('/clinic-service/{medicalServiceCategory}/success', [ClinicServiceSuccessController::class, 'index'])->name('clinic-service.success');

            Route::get('/medical-records', [MedicalRecordController::class, 'index'])->name('medical-record.browse');
            Route::get('/medical-records/show', [MedicalRecordController::class, 'show'])->name('medical-record.show');
        });
    });

    Route::prefix('partner')->name('partner.')->group(function() {
        Route::get('/login', [PartnerAuthenticatedSessionController::class, 'create'])->middleware('guest')->name('login');
        Route::post('/login', [PartnerAuthenticatedSessionController::class, 'store'])->middleware('guest');
        Route::get('/register', [RegisterController::class, 'create'])->name('register');
        Route::post('/register', [RegisterController::class, 'store']);
        Route::get('/success', [RegisterSuccessController::class, 'index'])->middleware('auth')->name('register.success');
        Route::post('/logout', [PartnerAuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');
        Route::get('/waiting-verification', [WaitingVerification::class, 'index'])->middleware(['auth', 'verified'])->name('waiting-verification');

        Route::middleware(['auth', 'verified', 'medical_people_status_accepted'])->group(function() {
            Route::get('/dashboard', [PartnerDashboardController::class, 'index'])->name('dashboard');
            Route::put('/profile/avatar', [UpdateAvatarController::class, 'update'])->name('dashboard.update-avatar');
            Route::put('/profile', [ProfilePartnerController::class, 'update'])->name('profile.update');
            Route::put('/account-bank', [BankAccountController::class, 'update'])->name('profile.account-bank');

            Route::middleware(['only.ajax'])->group(function() {
                Route::get('/orders/view/{booking}', [OrderController::class, 'show'])->name('orders.show');
                Route::get('/orders/map/{booking}', [MapOrderController::class, 'show'])->name('orders.map');
                Route::get('/orders/payment-check/{invoice}', [PaymentCheckOrderController::class, 'show'])->name('orders.payment-check');
                Route::post('/orders/passcode-check/{booking}', [BookingPasscodeController::class, 'store'])->name('orders.passcode-check');

                Route::get('/orders/popup-handling/{booking}', [PopupHandlingOrderController::class, 'show'])->name('orders.popup-handling');
                Route::get('/orders/popup-medical-record/{booking}', [PopupMedicalRecordOrderController::class, 'show'])->name('orders.popup-medical-record');
                Route::get('/orders/popup-additional-services/{booking}', [PopupAdditionalServicesOrderController::class, 'show'])->name('orders.popup-additional-service');
                Route::post('/orders/popup-confirmation-additional-services/{booking}', [PopupConfirmationAdditionalServiceOrderController::class, 'show'])->name('orders.popup-confirmation-additional-service');

app/Models/ClinicBooking.php
<?php

namespace App\Models;

use App\Enums\BookingStatus;
use App\Enums\ClinicBookingStatus;
use App\Enums\Gender;
use App\Traits\CanGenerateIdNumber;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * App\Models\ClinicBooking
 *
 * @property int $id
 * @property int $patient_id
 * @property int $medical_service_id
 * @property string $number
 * @property ClinicBookingStatus $status
 * @property string $name
 * @property string $phone_number
 * @property string $bod
 * @property Gender $gender
 * @property string $history_of_disease_allergies
 * @property string $main_symptom
 * @property string $special_request
 * @property string $address
 * @property bool $is_self
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read MedicalService $medical_service
 * @property-read Patient $patient
 * @method static Builder|ClinicBooking newModelQuery()
 * @method static Builder|ClinicBooking newQuery()
 * @method static Builder|ClinicBooking query()
 * @method static Builder|ClinicBooking whereAddress($value)
 * @method static Builder|ClinicBooking whereBod($value)
 * @method static Builder|ClinicBooking whereCreatedAt($value)
 * @method static Builder|ClinicBooking whereGender($value)
 * @method static Builder|ClinicBooking whereHistoryOfDiseaseAllergies($value)
 * @method static Builder|ClinicBooking whereId($value)
 * @method static Builder|ClinicBooking whereIsSelf($value)
 * @method static Builder|ClinicBooking whereMainSymptom($value)
 * @method static Builder|ClinicBooking whereMedicalServiceId($value)
 * @method static Builder|ClinicBooking whereName($value)
 * @method static Builder|ClinicBooking whereNumber($value)
 * @method static Builder|ClinicBooking wherePatientId($value)
 * @method static Builder|ClinicBooking wherePhoneNumber($value)
 * @method static Builder|ClinicBooking whereSpecialRequest($value)
 * @method static Builder|ClinicBooking whereStatus($value)
 * @method static Builder|ClinicBooking whereUpdatedAt($value)
 * @mixin Eloquent
 */
class ClinicBooking extends Model
{
    use HasFactory, CanGenerateIdNumber;

    protected static string $id_number_column = "number";

    protected $casts = [
        'status' => ClinicBookingStatus::class,
        'gender' => Gender::class,
        'dob' => 'date',
        'is_self' => 'boolean',
    ];

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::creating(function (ClinicBooking $clinicBooking) {
            if (! $clinicBooking->status) {
                $clinicBooking->status = ClinicBookingStatus::SUBMITTED();
            }

            $clinicBooking->number = ClinicBooking::generateIdNumber();
        });
    }

    /**
     * Patient
     *
     * @return BelongsTo
     */
    public function patient(): BelongsTo
    {
        return $this->belongsTo(Patient::class);
    }

    /**
     * Medical Service
     *
     * @return BelongsTo
     */
    public function medical_service(): BelongsTo
    {
        return $this->belongsTo(MedicalService::class);
    }

}

app/Http/Controllers/Theteam/ClinicBookingController.php
<?php

namespace App\Http\Controllers\Theteam;

use App\DataTables\ClinicBookingDatatable;
use App\Http\Controllers\Controller;
use App\Models\ClinicBooking;
use App\Enums\ClinicBookingStatus;
use App\Models\MedicalServiceCategory;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ClinicBookingController extends Controller
{
    public function index(MedicalServiceCategory $medicalServiceCategory, ClinicBookingDatatable $clinicBookingDatatable)
    {
        return $clinicBookingDatatable
            ->with('category', $medicalServiceCategory)
            ->render('pages.clinic-bookings.browse');
    }


    /**
     * Display the specified resource.
     *
     * @param ClinicBooking $clinicBooking
     * @return Factory|View|Application
     */
    public function show(ClinicBooking $clinicBooking): Factory|View|Application
    {
        //$this->authorize('view', $booking);

        return view('pages.clinic-bookings.show', compact('clinicBooking'));
    }


    public function update(Request $request, ClinicBooking $clinicBooking)
    {
        //$this->authorize('view', $booking);
        $clinicBooking->status = ClinicBookingStatus::DONE();
        $clinicBooking->save();


        return back()->with([
            'message' => 'Successfully mark as done the booking',
        ]);

    }



}

app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): \Illuminate\Contracts\View\View|\Illuminate\Contracts\Support\Htmlable|\Closure|string
    {
        return theme()->getView('layout.master');
    }
}

resources/views/pages/clinic-bookings/_action-menu.blade.php
<!--begin::Action--->
<td class="text-end">
    <a href="{{ route('clinic-bookings.show', $booking->id) }}" class="btn btn-sm btn-light-primary btn-active-primary">
        View
    </a>
</td>
<!--end::Action--->

resources/views/pages/clinic-bookings/_status.blade.php
{!! $booking->status->toBadge() !!}

resources/views/pages/clinic-bookings/browse.blade.php
<x-base-layout>

    <!--begin::Card-->
    <div class="card">
        <!--begin::Card body-->
        <div class="card-body pt-6">
            <!--begin::Table-->
            {{ $dataTable->table() }}
            <!--end::Table-->

            {{-- Inject Scripts --}}
            @section('scripts')
                {{ $dataTable->scripts() }}
            @endsection
        </div>
        <!--end::Card body-->
    </div>
    <!--end::Card-->

</x-base-layout>

resources/views/pages/clinic-bookings/show.blade.php
<x-base-layout>

    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container-xxl">
            <!--begin::Layout-->
            <div class="d-flex flex-column flex-lg-row">
                <!--begin::Content-->
                <div class="flex-lg-row-fluid me-lg-15 order-2 order-lg-1 mb-10 mb-lg-0">
                    <!--begin::Card-->
                    <div class="card card-flush pt-3 mb-5 mb-xl-10">
                        <!--begin::Card header-->
                        <div class="card-header">
                            <!--begin::Card title-->
                            <div class="card-title">
                                <h2 class="fw-bolder">Booking Details {{$clinicBooking->number}}</h2>
                            </div>
                            <!--begin::Card title-->
                        </div>
                        <!--end::Card header-->
                        <!--begin::Card body-->
                        <div class="card-body pt-3">
                            <!--begin::Section-->
                            <div class="mb-10">
                                <!--begin::Title-->
                                <h5 class="mb-4">Patient detail:</h5>
                                <!--end::Title-->
                                <!--begin::Details-->
                                <div class="d-flex flex-wrap py-5">
                                    <!--begin::Row-->
                                    <div class="flex-equal me-5">
                                        <!--begin::Details-->
                                        <table class="table fs-6 fw-bold gs-0 gy-2 gx-2 m-0">
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400 min-w-175px w-175px">Email:</td>
                                                <td class="text-gray-800 min-w-200px">
                                                    <a href="{{ route('patients.show', $clinicBooking->patient->id) }}" class="text-gray-800 text-hover-primary">{{ $clinicBooking->patient->user->email }}</a>
                                                </td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Name:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->name }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Address:</td>
                                                <td class="text-gray-800">{!! nl2br($clinicBooking->patient->address) !!}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Kelurahan:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->postal_code->urban }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Kecamatan:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->postal_code->sub_district }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">City:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->postal_code->city }}</td>
                                            </tr>

                                            <tr>
                                                <td class="text-gray-400">Services : </td>
                                                <td class="text-gray-800">{{ $clinicBooking->medical_service->name }}</td>
                                            </tr>

                                            <tr>
                                                <td class="text-gray-400">Status : </td>
                                                <td class="text-gray-800">
                                                @if ($clinicBooking->status == 'SUBMITTED')
                                                    <form method="POST" action="{{ route('clinic-bookings.update', $clinicBooking->id) }}">
                                                        @csrf
                                                        @method("PUT")
                                                        <button type="submit" class="btn btn-sm btn-light-warning btn-active-warning">{{ $clinicBooking->status }}</button>
                                                    </form>
                                                @else
                                                    {!! $clinicBooking->status->toBadge() !!}</td>
                                                @endif    
                                                
                                            </tr>
                                            <!--end::Row-->
                                        </table>
                                        <!--end::Details-->
                                    </div>
                                    <!--end::Row-->
                                    <!--begin::Row-->
                                    <div class="flex-equal">
                                        <!--begin::Details-->
                                        <table class="table fs-6 fw-bold gs-0 gy-2 gx-2 m-0">
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Phone:</td>
                                                <td class="text-gray-800"><a target="_blank" href="https://wa.me/{{$clinicBooking->patient->phoneNumber()}}">{{ $clinicBooking->patient->phone_number }}</a></td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400 min-w-175px w-175px">Birthday:</td>
                                                <td class="text-gray-800 min-w-200px">{{ $clinicBooking->patient->bod->format('d F Y') }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400 min-w-175px w-175px">Gender:</td>
                                                <td class="text-gray-800 min-w-200px">{{ $clinicBooking->patient->gender->value }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Nationality:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->nationality }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Province:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->postal_code->province->province_name }}</td>
                                            </tr>
                                            <!--end::Row-->
                                            <!--begin::Row-->
                                            <tr>
                                                <td class="text-gray-400">Postal Code:</td>
                                                <td class="text-gray-800">{{ $clinicBooking->patient->postal_code->postal_code }}</td>
                                            </tr>
                                            <!--end::Row-->
                                        </table>
                                        <!--end::Details-->
                                    </div>
                                    <!--end::Row-->
                                </div>
                                <!--end::Row-->
                            </div>
                            <!--end::Section-->
                          
                        </div>
                        <!--end::Card body-->
                    </div>
              
                    <!--end::Card-->
                    <!--begin::Card-->
                    <div class="card card-flush pt-3 mb-5 mb-xl-10">
                        <!--begin::Card header-->
                        <div class="card-header">
                            <!--begin::Card title-->
                            <div class="card-title">
                                <h2>History Clinic Services</h2>
                            </div>
                            <!--end::Card title-->
                        </div>
                        <!--end::Card header-->
                        <!--begin::Card body-->
                        <div class="card-body pt-0">
                            <!--begin::Table wrapper-->
                            <div class="table-responsive">
                                <!--begin::Table-->
                                <table class="table align-middle table-row-dashed fs-6 text-gray-600 fw-bold gy-5" id="kt_table_customers_events">
                                    <!--begin::Table body-->
                                    <tbody>

                                    <!--begin::Table row-->
                                    <tr>
                                        <!--begin::Event=-->
                                        <td class="min-w-400px">
                                            <a href="#" class="fw-bolder text-gray-800 text-hover-primary me-1">CS2202-0003</a> Service Calm Clinic - Psychologist</td>
                                        <!--end::Event=-->
                                        <!--begin::Timestamp=-->
                                        <td class="pe-0 text-gray-600 text-end min-w-200px">15 Apr 2021</td>
                                        <!--end::Timestamp=-->
                                    </tr>
                                    <!--end::Table row-->
                                    
                               
                             
                                    <!--end::Table row-->
                                    </tbody>
                                    <!--end::Table body-->
                                </table>
                                <!--end::Table-->
                            </div>
                            <!--end::Table wrapper-->
                        </div>
                        <!--end::Card body-->
                    </div>
                    <!--end::Card-->
                </div>
                <!--end::Content-->
                <!--begin::Sidebar-->
                
                <!--end::Sidebar-->
            </div>
            <!--end::Layout-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->



    @section('scripts')
        <script type="text/javascript">
            window.booking_id = {{ $clinicBooking->id }}
      
        </script>
    @endsection

</x-base-layout>